# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 09:51
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('fps', models.SmallIntegerField(default=10)),
                ('analysis', models.SmallIntegerField(choices=[(1, 'Full'), (2, 'Move'), (3, 'Record')], default=1)),
                ('resolution', models.SmallIntegerField(choices=[(1, '360'), (2, '480'), (3, '720'), (4, 'HD'), (5, '2K'), (6, '4K')], default=1)),
                ('storage_life', models.IntegerField(default=7)),
                ('compress_level', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('port', models.IntegerField()),
                ('notify_email', models.CharField(max_length=500, null=True)),
                ('notify_phone', models.CharField(max_length=20, null=True)),
                ('notify_events', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('notify_time_start', models.TimeField(default=datetime.time(0, 0))),
                ('notify_time_stop', models.TimeField(default=datetime.time(0, 0))),
                ('notify_alert_level', models.SmallIntegerField(default=1)),
                ('notify_send_email', models.BooleanField(default=False)),
                ('notify_send_sms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Camera2CameraGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CameraGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.GenericIPAddressField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='camera2cameragroup',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.CameraGroup'),
        ),
        migrations.AddField(
            model_name='camera2cameragroup',
            name='camera_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Camera'),
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.CameraGroup'),
        ),
        migrations.AddField(
            model_name='camera',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
        ),
        migrations.AddField(
            model_name='camera',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Server'),
        ),
    ]
