# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-14 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcamera',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cameragroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
        ),
        migrations.AddField(
            model_name='camera2quadrator',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Camera'),
        ),
        migrations.AddField(
            model_name='camera2quadrator',
            name='quadrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Quadrator'),
        ),
        migrations.AddField(
            model_name='camera2cameragroup',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.CameraGroup'),
        ),
        migrations.AddField(
            model_name='camera2cameragroup',
            name='camera_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Camera'),
        ),
        migrations.AddField(
            model_name='camera',
            name='camera_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.CameraGroup'),
        ),
        migrations.AddField(
            model_name='camera',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
        ),
        migrations.AddField(
            model_name='camera',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.Server'),
        ),
    ]
