# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-15 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_auto_20190415_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='local_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
