# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-18 08:30
from __future__ import unicode_literals

from django.db import migrations, models

def gen_coords(apps, schema_editor):
    QuadratorModel = apps.get_model('cameras', 'Quadrator')
    print('generating coords');
    for q in QuadratorModel.objects.all():
        print('generating coords for quadrator ', q.id);
        for idx, cam in enumerate(q.camera2quadrator_set.all()):
            print('generating coords for camera ', cam.id);
            cam.x = idx % q.num_cam_x;
            cam.y = int(idx / q.num_cam_x);
            print('x: ', cam.x);
            print('y: ', cam.y);
            cam.save();

class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_server_local_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera2quadrator',
            name='cols',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='camera2quadrator',
            name='rows',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='camera2quadrator',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera2quadrator',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(gen_coords),
    ]
