# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('cameras', '0004_flexi_quadrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadratorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
            ],
        ),
        migrations.AlterField(
            model_name='cameragroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='quadrator',
            name='quadrator_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.QuadratorGroup'),
        ),
    ]
