# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-10-25 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_auto_20190821_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='add_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]