# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-10-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_camera_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='add_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]