# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-12-04 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_auto_20191025_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='from_queue_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='camera',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cameras.Storage'),
        ),
    ]
