# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-12-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_auto_20191204_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='mac_address',
            field=models.CharField(default='02420A0A6E0A', max_length=100),
        ),
    ]
