# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-12-11 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0010_server_mac_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(max_length=100)),
                ('weekdays', models.CharField(default=None, max_length=50, null=True)),
                ('start_timestamp', models.CharField(default=None, max_length=50, null=True)),
                ('stop_timestamp', models.CharField(default=None, max_length=50, null=True)),
                ('start_daytime', models.CharField(default=None, max_length=50, null=True)),
                ('stop_daytime', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='schedule_job_start',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='schedule_job_stop',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='schedule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cameras.CameraSchedule'),
        ),
    ]
