# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-12-12 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0011_auto_20191211_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
