# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-01-24 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0014_auto_20200116_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='address_secondary',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]