# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-02-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0016_auto_20200206_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='uid',
            new_name='time_uuid',
        ),
        migrations.AddField(
            model_name='camera',
            name='uuid',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]