# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-03-05 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0016_auto_20200206_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('error_code', models.IntegerField()),
                ('error_type', models.CharField(max_length=200)),
                ('error_message', models.TextField()),
            ],
        ),
    ]
