# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-03-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0017_cameralog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameralog',
            old_name='add_time',
            new_name='error_time',
        ),
        migrations.RemoveField(
            model_name='cameralog',
            name='error_code',
        ),
        migrations.AddField(
            model_name='cameralog',
            name='module_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
