# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-03-06 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0018_auto_20200305_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameralog',
            name='error_type',
            field=models.IntegerField(default=0),
        ),
    ]
