"""
Django settings for theorema project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd-%dc+$+3*dt6bkb8pnfiu64qrc#df0o27rynbqbt6uval(6r5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'allauth',
    'rest_auth',
    'rest_auth.registration',
    'djcelery_email',

    'theorema.users',
    'theorema.cameras',
    'theorema.orgs',
    'theorema.other',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'theorema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'theorema/templates'), os.path.join(BASE_DIR, 'theorema-frontend/dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'theorema.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = { 
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'theorema',
        'USER': 'theorema',
        'PASSWORD': 'theorema',
        'HOST': 'localhost',
        'PORT': 5432,
        'CONN_MAX_AGE': None
    }   
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


AUTH_USER_MODEL = 'users.User'

ROOT = os.path.dirname(os.path.realpath(__file__))
PROJECT_STATIC_ROOT = os.path.join(BASE_DIR, 'theorema-frontend/dist/static')
STATIC_ROOT = os.path.join(ROOT, 'static_collect/')
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    PROJECT_STATIC_ROOT,
)


MEDIA_ROOT = os.path.join(ROOT, 'media/')
MEDIA_URL = '/media/'
ARCHDIR = '/home/_VideoArchive/'


CELERY_BROKER_URL='amqp://teorema:teorema@0.0.0.0:5672/theorema',
CELERY_RESULT_BACKEND='amqp://teorema:teorema@0.0.0.0:5672/theorema'

try:
    from theorema.settings_local import *
except ImportError as exc:
    __import__('warnings').warn("Can't load local settings: {}".format(str(exc)))

if DEBUG:
    lk_url = 'http://127.0.0.1:5000/'
else:
    lk_url = 'https://oculars.net/'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'djcelery_email.backends.CeleryEmailBackend'
EMAIL_HOST = 'ex.teorema.info'
EMAIL_HOST_USER = 'analitika@teorema.info'
EMAIL_HOST_PASSWORD = 'Lo0k@ndCry!'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
