# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-14 23:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcularUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_hash', models.CharField(max_length=50)),
                ('max_cam', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('remote_id', models.IntegerField(default=0)),
                ('type', models.CharField(default='offline', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
    ]
